//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial2.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Prenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prenda()
        {
            this.FotoPrendas = new HashSet<FotoPrenda>();
        }
    
        public int IdPrenda { get; set; }
        public string TipoPrenda { get; set; }
        public string Descripcion { get; set; }
        public float Valor { get; set; }
        public string Cliente { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FotoPrenda> FotoPrendas { get; set; }
    }
}
